name: scredex_mobile
description: Scredex Flutter app
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  flutter_riverpod: ^2.5.1
  scredex_design_system:
    path: ../../packages/design_system
  http: ^1.2.1
  intl: ^0.19.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
