name: scredex_mobile
description: Scredex Flutter app
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  lottie: ^2.6.0
  http: ^0.13.6
  scredex_design_system:
    path: ../../packages/design_system
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/animations/scredex_logo.json
    - assets/stubs/billers.json
